# Generated by Django 5.0.3 on 2024-03-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_alter_category_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="assigned_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
